// Code generated by "stringer -type=ISAExt -linecomment"; DO NOT EDIT.

package zydis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ISAExtInvalid-0]
	_ = x[ISAExtADOX_ADCX-1]
	_ = x[ISAExtAES-2]
	_ = x[ISAExtAMD3DNOW-3]
	_ = x[ISAExtAVX-4]
	_ = x[ISAExtAVX2-5]
	_ = x[ISAExtAVX2GATHER-6]
	_ = x[ISAExtAVX512EVEX-7]
	_ = x[ISAExtAVX512VEX-8]
	_ = x[ISAExtAVXAES-9]
	_ = x[ISAExtBase-10]
	_ = x[ISAExtBMI1-11]
	_ = x[ISAExtBMI2-12]
	_ = x[ISAExtCET-13]
	_ = x[ISAExtCLDEMOTE-14]
	_ = x[ISAExtCLFLUSHOPT-15]
	_ = x[ISAExtCLFSH-16]
	_ = x[ISAExtCLWB-17]
	_ = x[ISAExtCLZero-18]
	_ = x[ISAExtF16C-19]
	_ = x[ISAExtFMA-20]
	_ = x[ISAExtFMA4-21]
	_ = x[ISAExtGFNI-22]
	_ = x[ISAExtINVPCID-23]
	_ = x[ISAExtKNC-24]
	_ = x[ISAExtKNCE-25]
	_ = x[ISAExtKNCV-26]
	_ = x[ISAExtLongMode-27]
	_ = x[ISAExtLZCNT-28]
	_ = x[ISAExtMMX-29]
	_ = x[ISAExtMonitor-30]
	_ = x[ISAExtMonitorX-31]
	_ = x[ISAExtMOVBE-32]
	_ = x[ISAExtMOVDIR-33]
	_ = x[ISAExtMPX-34]
	_ = x[ISAExtPadlock-35]
	_ = x[ISAExtPause-36]
	_ = x[ISAExtPCLMULQDQ-37]
	_ = x[ISAExtPConfig-38]
	_ = x[ISAExtPKU-39]
	_ = x[ISAExtPrefetchWT1-40]
	_ = x[ISAExtPT-41]
	_ = x[ISAExtRDPID-42]
	_ = x[ISAExtRDRAND-43]
	_ = x[ISAExtRDSEED-44]
	_ = x[ISAExtRDTSCP-45]
	_ = x[ISAExtRDWRFSGS-46]
	_ = x[ISAExtRTM-47]
	_ = x[ISAExtSGX-48]
	_ = x[ISAExtSGX_ENCLV-49]
	_ = x[ISAExtSHA-50]
	_ = x[ISAExtSMAP-51]
	_ = x[ISAExtSMX-52]
	_ = x[ISAExtSSE-53]
	_ = x[ISAExtSSE2-54]
	_ = x[ISAExtSSE3-55]
	_ = x[ISAExtSSE4-56]
	_ = x[ISAExtSSE4A-57]
	_ = x[ISAExtSSSE3-58]
	_ = x[ISAExtSVM-59]
	_ = x[ISAExtTBM-60]
	_ = x[ISAExtVAES-61]
	_ = x[ISAExtVMFUNC-62]
	_ = x[ISAExtVPCLMULQDQ-63]
	_ = x[ISAExtVTX-64]
	_ = x[ISAExtWAITPKG-65]
	_ = x[ISAExtX87-66]
	_ = x[ISAExtXOP-67]
	_ = x[ISAExtXSave-68]
	_ = x[ISAExtXSaveC-69]
	_ = x[ISAExtXSaveOPT-70]
	_ = x[ISAExtXSaveS-71]
}

const _ISAExt_name = "INVALIDADOX_ADCXAESAMD3DNOWAVXAVX2AVX2GATHERAVX512EVEXAVX512VEXAVXAESBASEBMI1BMI2CETCLDEMOTECLFLUSHOPTCLFSHCLWBCLZEROF16CFMAFMA4GFNIINVPCIDKNCKNCEKNCVLONGMODELZCNTMMXMONITORMONITORXMOVBEMOVDIRMPXPADLOCKPAUSEPCLMULQDQPCONFIGPKUPREFETCHWT1PTRDPIDRDRANDRDSEEDRDTSCPRDWRFSGSRTMSGXSGX_ENCLVSHASMAPSMXSSESSE2SSE3SSE4SSE4ASSSE3SVMTBMVAESVMFUNCVPCLMULQDQVTXWAITPKGX87XOPXSAVEXSAVECXSAVEOPTXSAVE"

var _ISAExt_index = [...]uint16{0, 7, 16, 19, 27, 30, 34, 44, 54, 63, 69, 73, 77, 81, 84, 92, 102, 107, 111, 117, 121, 124, 128, 132, 139, 142, 146, 150, 158, 163, 166, 173, 181, 186, 192, 195, 202, 207, 216, 223, 226, 237, 239, 244, 250, 256, 262, 270, 273, 276, 285, 288, 292, 295, 298, 302, 306, 310, 315, 320, 323, 326, 330, 336, 346, 349, 356, 359, 362, 367, 373, 381, 386}

func (i ISAExt) String() string {
	if i < 0 || i >= ISAExt(len(_ISAExt_index)-1) {
		return "ISAExt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ISAExt_name[_ISAExt_index[i]:_ISAExt_index[i+1]]
}
